version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
    command: -c /etc/nats/nats.conf
    volumes:
      - ./nats/config:/etc/nats
    networks:
      - net
    restart: unless-stopped

  signaling:
    image: strukturag/nextcloud-spreed-signaling:latest
    container_name: nextcloud-signaling
    depends_on:
      - nats
    ports:
      - "8084:8084"
    volumes:
      - ./config:/etc/signaling
    environment:
      - NATS_URL=nats://signaling:verysecretpass@nats:4222
    labels:
      - traefik.enable=true
      - traefik.http.routers.signaling.rule=Host(`signaling.yesj.in`) && PathPrefix(`/spreed`)
      - traefik.http.middlewares.stripspreed.stripprefix.prefixes=/spreed
      - traefik.http.routers.signaling.middlewares=stripspreed
      - traefik.http.routers.signaling.entrypoints=websecure
      - traefik.http.routers.signaling.tls.certresolver=letsencrypt
      - traefik.http.services.signaling.loadbalancer.server.port=8084
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge
