version: '3.7'

services:
  signaling:
    image: strukturag/nextcloud-spreed-signaling:latest
    container_name: nextcloud-signaling
    ports:
      - "8080:8080"
    environment:
      - SIGNALING_API_KEY=${SIGNALING_API_KEY}
    volumes:
      - ./config:/config
    restart: unless-stopped
