version: '3'
services:
  signaling:
    image: strukturag/nextcloud-spreed-signaling:latest
    ports:
      - "8084:8084"
    volumes:
      - ./server.conf:/etc/signaling/server.conf
    depends_on:
      - nats
      - janus
  nats:
    image: nats:latest
  janus:
    image: meetecho/janus-gateway
    ports:
      - "8188:8188"
