version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
    command: >
      -c /etc/nats/nats.conf
    volumes:
      - ./nats/config:/etc/nats
    restart: unless-stopped

  signaling:
    image: strukturag/nextcloud-spreed-signaling:latest
    container_name: nextcloud-signaling
    depends_on:
      - nats
    ports:
      - "8084:8084"
    volumes:
      - ./signaling/config:/config
    environment:
      - SIGNALING_SECRET=${SIGNALING_SECRET}
      - SIGNALING_AUTH_SHARED_SECRET=${SIGNALING_SHARED_SECRET}
      - SIGNALING_NATS_URL=nats://signaling:${NATS_PASSWORD}@nats:4222
    labels:
      - traefik.enable=true
      - traefik.http.routers.signaling.rule=Host(`${SIGNALING_DOMAIN}`)
      - traefik.http.routers.signaling.entrypoints=websecure
      - traefik.http.routers.signaling.tls.certresolver=letsencrypt
    restart: unless-stopped

networks:
  default:
