version: '3.8'

services:
  talk_hpb:
    image: ghcr.io/nextcloud-releases/aio-talk:latest
    container_name: talk_hpb
    init: true
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "8081:8081/tcp"
