version: '3.8'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    environment:
      - NATS_USER=signaling
      - NATS_PASSWORD=verysecretpass
    restart: unless-stopped

  janus:
    image: canyan/janus-gateway:latest
    ports:
      - "8188:8188"
      - "8088:8088"
      - "7088-7090:7088-7090/udp"
    volumes:
      - ./conf:/usr/local/etc/janus
    restart: unless-stopped
  signaling:
    image: strukturag/nextcloud-spreed-signaling:latest
    volumes:
      - ./conf/signaling/server.conf:/etc/signaling/server.conf
    environment:
      - SIGNALING_CONFIG=/etc/signaling/server.conf
    ports:
      - "8080:8080"
    depends_on:
      - nats
      - janus
    restart: unless-stopped