version: '3.8'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    restart: unless-stopped

    janus:
    image: canyan/janus-gateway:latest
    ports:
      - "8188:8188"
      - "8088:8088"
      - "7088-7090:7088-7090/udp"
    volumes:
      - ./conf:/usr/local/etc/janus
    restart: unless-stopped
