version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
    command: >
      -c /etc/nats/nats.conf
    volumes:
      - ./nats/config:/etc/nats
    networks:
      - localnet
    restart: unless-stopped

  signaling:
    image: strukturag/nextcloud-spreed-signaling:latest
    container_name: nextcloud-signaling
    depends_on:
      - nats
    ports:
      - "8084:8084"
    volumes:
      - ./signaling/config:/config
    environment:
      - SIGNALING_SECRET=${SIGNALING_SECRET}
      - SIGNALING_AUTH_SHARED_SECRET=${SIGNALING_AUTH_SHARED_SECRET}
      - SIGNALING_SESSION_HASH_KEY=${SIGNALING_SESSION_HASH_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.signaling.rule=Host(`signaling.yesj.in`) && PathPrefix(`/spreed`)
      - traefik.http.middlewares.stripspreed.stripprefix.prefixes=/spreed
      - traefik.http.routers.signaling.middlewares=stripspreed
      - traefik.http.routers.signaling.entrypoints=websecure
      - traefik.http.routers.signaling.tls.certresolver=letsencrypt
      - traefik.http.services.signaling.loadbalancer.server.port=8084
    networks:
      - localnet
    restart: unless-stopped

networks:
  localnet:
    driver: bridge
